# Title and description will feature on the site!
title: Ezra Haddad
description: 
baseurl: "" # The site subpath -- for example, "/blog"
url: "https://ezrahaddad.github.io" # http://example.com for example.

# Want to give people your email?
email: ehaddad@student.ethz.ch

# Enter your GitHub username.
github: test

# Pick from "twitter" or "fediverse".
social: twitter
# If "fediverse", enter the whole url for username:
social_username: test

permalink: /:year/:month/:title
